---
# On désactive les mises à jour système pour ne pas bloquer sur le verrou APT (lock)
# Ton Raspberry Pi est déjà prêt, on se concentre sur les containers.

- name: Installation des outils de base (si nécessaire)
  apt:
    name:
      - curl
      - git
      - htop
    state: present
  ignore_errors: true
