---
- name: Création du dossier Nexus
  file:
    path: "/home/{{ ansible_user }}/nexus"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Déploiement du docker-compose Nexus
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/nexus/docker-compose.yml"

- name: Lancement de Nexus
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/nexus"
    state: present

- name: Attente du démarrage de Nexus (Cela peut être long sur un Pi !)
  wait_for:
    port: 8081
    delay: 30
    timeout: 600
