---
- name: Création du dossier racine Nexus
  file:
    path: "/home/{{ ansible_user }}/nexus/nexus-data"
    state: directory
    mode: '0777'

- name: Correction FORCE des permissions via Docker (Gourou Style)
  shell: |
    docker run --rm -v /home/{{ ansible_user }}/nexus/nexus-data:/data alpine chown -R 200:200 /data
  become: true

- name: Déploiement du docker-compose Nexus
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/nexus/docker-compose.yml"

- name: Lancement de Nexus
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/nexus"
    state: present

- name: Attente du démarrage de Nexus (Cela peut être long sur un Pi !)
  wait_for:
    port: 8081
    delay: 30
    timeout: 600
