---
- name: Nettoyage des anciens fichiers de clés et dépôts Docker
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/keyrings/docker.gpg
    - /etc/apt/keyrings/docker.asc
    - /etc/apt/sources.list.d/docker.list

- name: Installation des dépendances Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Création du dossier pour les clés GPG
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Ajout de la clé GPG Docker (Méthode moderne)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Ajout du dépôt Docker (Correction pour Ubuntu)
  apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Installation de Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ajout de l'utilisateur au groupe docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Création du réseau 'proxy'
  docker_network:
    name: proxy
    state: present
