---
- name: Création du dossier Proxy
  file:
    path: "/home/{{ ansible_user }}/proxy"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Déploiement du docker-compose NPM
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/proxy/docker-compose.yml"

- name: Lancement de Nginx Proxy Manager
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/proxy"
    state: present
